name: Deploy React App

on:
  push:
    branches:
      - main  # Trigger the action when changes are pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Set the Node.js version you use

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Deploy to Hostinger
      uses: appleboy/ftp-action@v1
      with:
        host: ftp://178.16.136.201
        username: u463110696.fullycrud.rameshgondart.com
        password: RameshShyamJi13@
        port: 21
        source: './build/*'  # React app build output folder
        target: '/public_html/'  # Path on Hostinger server to deploy
