name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Change this to your branch name if it's not "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload Build Folder to Hostinger
      uses: sebastianpopp/ftp-deploy-action@v2.0.0
      with:
        server: ftp://178.16.136.201         # Replace with your Hostinger FTP Server
        username: u463110696.fullycrud.rameshgondart.com       # Replace with your FTP username
        password: RameshShyamJi13@  
        port: 21  # Replace with your FTP password
        local-dir: build/                  # Only deploy the "build" folder
        server-dir: public_html/           # Deploy to Hostinger's public_html folder
